grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: KNeighborsClassifier
    module: sklearn.neighbors
    params:
      algorithm: kd_tree
      weights: uniform
      n_neighbors: 3
    search_param_grid:
      algorithm:
      - auto
      - ball_tree
      - kd_tree
      - brute
      weights:
      - uniform
      - distance
      n_neighbors:
      - 3
      - 4
      - 7

      
  module_1:
    class: CatBoostClassifier
    module: catboost
    params:
      depth: 6
      min_data_in_leaf: 1
    search_param_grid:
      depth:
      - 6
      - 8
      - 10
      min_data_in_leaf:
      - 1
      - 3
      - 9